minProtein: 10
maxFat: 30
maxCalories: 500
number: 10
query: "chick"
query_recipes: "pasta"
id_for_taste:  69095
sweetness: 48.35
length_resp: 7
id_eqip:  1003464
calories: 899
carbs: 111g
fat: 45g
protein: 11g