name: Test API Spoonacular CI
run-name: ${{ github.actor }} is testing CI API Spoonacular
on:
  push:
      branches: [ "master" ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger -  ${{ github.event_name }}. "
      - run: echo "Running on a ${{ runner.os }}"
      - run: echo "Repository - ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: echo "This job's status is ${{ job.status }}."